---

- name: "Set facts"
  set_fact:
    container_dir: "{{ lxc_root }}/containers/{{ container_hostname }}"

- name: "Find customer NGINX configs"
  find:
    paths: "/etc/nginx/devtank/"
    patterns: "{{ customer_name }}.conf"
    recurse: yes
  register: customer_nginx_files

- name: "Remove NGINX configs"
  file:
    state: absent
    path: "{{ item }}"
  loop: "{{ customer_nginx_files.files|map(attribute='path')|list }}"

- name: "Reload NGINX"
  command: "{{ item }}"
  with_items:
    - "nginx -t"
    - "nginx -s reload"

- name: "Get MAC address"
  command: "awk '/lxc.net.0.hwaddr/ { print $3 }' \"{{ container_dir }}/lxc.container.conf\""
  register: container_hwaddr

- name: "Stop the container"
  command: "lxc-stop '{{ container_hostname }}'"
  ignore_errors: yes

- name: "Delete snapshots"
  command: "snapper -c {{ container_hostname }} list --columns number | tail -n +4 | xargs snapper -c {{ container_hostname }} delete"
  ignore_errors: yes

- name: "Delete snapper config"
  command: "snapper -c {{ container_hostname }} delete-config"
  ignore_errors: yes

- name: "Delete the container subvolume"
  command: "btrfs subvolume delete '{{ container_dir }}'"

- name: "Delete DHCP entry"
  lineinfile:
    path: "/etc/lxc/dnsmasq.conf"
    regexp: "dhcp-host={{ container_hwaddr.stdout }}.+"
    state: absent

- name: "Delete cached DHCP lease"
  lineinfile:
    path: "/var/lib/misc/dnsmasq.lxcbr0.leases"
    regexp: ".*{{ container_hwaddr.stdout }}.*"
    state: absent

- name: "Delete hosts entry"
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*{{ container_hostname }}.*"
    state: absent

- name: "Restart lxc-net"
  systemd:
    name: lxc-net.service
    state: restarted
    enabled: yes

- name: Set default value to Undefined, if the variable is not defined
  set_fact:
    test_lets_encrypt: "{{ lookup('ansible.builtin.env', 'TEST_LETS_ENCRYPT', default=False) }}"

- name: Set certbot to use Pebble instance for testing cerbot in test/dev environment.
  set_fact:
     certbot_prefix : "REQUESTS_CA_BUNDLE=devtank.minica.pem "
     certbot_postfix : "--server https://10.10.1.1:14000/dir \
      --agree-tos \
      --no-verify-ssl \
      --http-01-port=5002 \
      --register-unsafely-without-email"
  when: test_lets_encrypt

- name: Set certbot to normal
  set_fact:
     certbot_prefix : ""
     certbot_postfix : ""
  when: not test_lets_encrypt

- name: Remove certificate for customer
  shell: |
    {{ certbot_prefix }}certbot delete --cert-name \
    {{ customer_name }}.{{ le_domain }} \
    {{ certbot_postfix }}

- name: "Note"
  debug:
    msg: "*** REMEMBER TO REMOVE ALL REFERENCE TO {{ container_hostname }} from nginx configs and reload! ***"

