---

- name: "Set facts"
  set_fact:
    container_dir: "{{ lxc_root }}/containers/{{ container_hostname }}"

- name: "Remove NGINX configs"
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_fileglob:
    path: "/etc/nginx/devtank/customers.*/{{ container_hostname }}.conf"

- name: "Reload NGINX"
  command: "{{ item }}"
  with_items:
    - "nginx -t"
    - "nginx -s reload"

- name: "Get MAC address"
  command: "awk '/lxc.net.0.hwaddr/ { print $3 }' \"{{ container_dir }}/lxc.container.conf\""
  register: container_hwaddr

- name: "Stop the container"
  command: "lxc-stop '{{ container_hostname }}'"
  ignore_errors: yes

- name: "Delete snapshots"
  command: "snapper -c {{ container_hostname }} list --columns number | tail -n +4 | xargs snapper -c {{ container_hostname }} delete"
  ignore_errors: yes

- name: "Delete snapper config"
  command: "snapper -c {{ container_hostname }} delete-config"
  ignore_errors: yes

- name: "Delete the container subvolume"
  command: "btrfs subvolume delete '{{ container_dir }}'"

- name: "Delete DHCP entry"
  lineinfile:
    path: "/etc/lxc/dnsmasq.conf"
    regexp: "dhcp-host={{ container_hwaddr.stdout }}.+"
    state: absent

- name: "Delete cached DHCP lease"
  lineinfile:
    path: "/var/lib/misc/dnsmasq.lxcbr0.leases"
    regexp: ".*{{ container_hwaddr.stdout }}.*"
    state: absent

- name: "Delete hosts entry"
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*{{ container_hostname }}.*"
    state: absent

- name: "Restart lxc-net"
  systemd:
    name: lxc-net.service
    state: restarted
    enabled: yes

- name: "Note"
  debug:
    msg: "*** REMEMBER TO REMOVE ALL REFERENCE TO {{ container_hostname }} from nginx configs and reload! ***"

