- name: "Check all variables are set"
  fail:
    msg: "All needed parameters are not set!"
  when:
    - customer_name is not defined

- name: "Set container name variable."
  ansible.builtin.set_fact:
    container_hostname: "{{ customer_name }}-svr"

- name: "Create container"
  import_tasks: create.yaml
  when: create_container == True

- name: "Delete container"
  import_tasks: delete.yaml
  when: delete_container == True
