- name: "Check all variables are set"       
  fail:             
    msg: "All needed parameters are not set!" 
  when:                                     
    - container_hostname is not defined

- name: "Create container"
  import_tasks: create.yaml
  when: create_container == True

- name: "Delete container"
  import_tasks: delete.yaml
  when: delete_container == True
