- hosts: "{{ target }}"
  tasks:
    - name: Check for btrfs /srv
      shell: |
        if [ -e /srv ]
        then
          srv_fs=$(df /srv -T | awk '/dev/ { print $2 }')
          if [ "$srv_fs" == 'btrfs' ]
          then
            echo "Already btrfs /srv"
            exit -1
          fi
        else
          root_fs=$(df / -T | awk '/dev/ { print $2 }')
          if [ "$root_fs" == 'btrfs' ]
          then
            echo "Already btrfs root or /srv"
            exit -1
          fi
          mkdir  -v -p -m 0755 -p /srv
        fi

    - name: Install required packages
      apt:
        name:
          - btrfs-progs
          - kexec-tools
          - git
        update_cache: yes

    - name: Clone Btrfs live upgrade git repo.
      ansible.builtin.git:
        repo: https://git.devtank.co.uk/Devtank/osm-ansible.git
        dest: /srv/osm-lxc
        single_branch: yes
        version: dev_test_env

    - name: Prepare Btrfs upgrade
      shell: |
        cd /srv/osm-lxc/orchestrator/env/upgrade
        git submodule init
        git submodule update
        ./make_btr.sh

    - name: Perform Upgrade Reboot
      reboot:
        reboot_command: /srv/osm-lxc/orchestrator/env/upgrade/mk_initrc/kexec.sh /srv/osm-lxc/orchestrator/env/upgrade/make_btrfs.cpio.gz
        connect_timeout: 120
        msg: Kexec reboot

    - name: Setup OSM HOST
      import_tasks: ./osmhost_from_btrfs.yaml
