- hosts: "{{ target }}"
  tasks:
    # - name: Setup for fake SSL
    #   shell: |
    #     # Fake up LetsEncrypt
    #     mkdir -p /etc/letsencrypt/live/{{ osm_host_name }}.{{ osm_domain }}
    #     openssl req -x509 -nodes -newkey rsa:4096 -days 1\
    #         -keyout "/etc/letsencrypt/live/{{ osm_host_name }}.{{ osm_domain }}/privkey.pem" \
    #         -out "/etc/letsencrypt/live/{{ osm_host_name }}.{{ osm_domain }}/fullchain.pem" \
    #         -subj '/CN=localhost' > /dev/null
    #     mkdir -p /etc/letsencrypt/renewal/
    #     echo "authenticator = standalone" > /etc/letsencrypt/renewal/{{ osm_host_name }}.{{ osm_domain }}.conf
    #   when: fake_osm_host is defined

    - name: Setup OSM HOST
      import_tasks: ./osmhost_setup.yaml

    - name: Ready for faking customer setup
      shell: |
        echo "SKIP_LETS_ENCRYPT=1" >> /etc/environment
        echo "Defaults env_keep += SKIP_LETS_ENCRYPT" >> /etc/sudoers.d/osm-anisble
