#! /bin/sh

. /etc/disks 

if [ -z "$root_dev" ]; then echo "No root given!" ; exit -1; fi

root_uuid=$(blkid $root_dev -o udev | awk -F= '/ID_FS_UUID=/ {print $2}')

e2fsck -fvy $root_dev
btrfs-convert -L -p --uuid copy $root_dev
btrfs check $root_dev
mkdir /mnt
modprobe btrfs
mount $root_dev /mnt
btrfs subv del /mnt/ext2_saved
btrfs subv snap /mnt /mnt/@rootfs
rm -rf mnt/[a-z]*
btrfs balance start --full-balance mnt
sed -i -E "s|UUID=$root_uuid.+\$|UUID=$root_uuid	/	btrs	defaults,subvol=@rootfs	0	1|g" /mnt/@rootfs/etc/fstab

umount /mnt
mount -t btrfs /dev/vda3 -o subvol=@rootfs mnt

[ -z "$boot_dev" ] || mount $boot_dev /mnt/boot
[ -z "$efi_dev" ] || mount $efi_dev /mnt/boot/efi

mount --bind /dev /mnt/dev
mount --bind /dev/pts /mnt/dev/pts
mount --bind /proc /mnt/proc
mount --bind /sys /mnt/sys

chroot /mnt /usr/bin/apt install btrfs-progs
chroot /mnt /usr/sbin/update-initramfs -k all -u
chroot /mnt /usr/sbin/update-grub

reboot -f

