#! /bin/sh

. /etc/disks 

[ -n "$root_dev" ] || (echo No root given! ; exit -1)

root_uuid=$(blkid $root_dev -o udev | awk -F= '/ID_FS_UUID=/ {print $2}')

e2fsck -fvy $root_dev
btrfs-convert -L -p --uuid copy $root_dev
btrfs check $root_dev
mkdir /mnt
modprobe btrfs
mount $root_dev /mnt
btrfs subv del /mnt/ext2_saved
btrfs subv snap /mnt /mnt/@rootfs
rm -rf mnt/[a-z]*
btrfs balance start --full-balance mnt
sed -i -E "s|UUID=$root_uuid.+\$|UUID=$root_uuid	/	btrs	defaults,subvol=@rootfs	0	1|g" /mnt/@rootfs/etc/fstab

[ -z "$boot_dev" ] || mount $boot_dev /mnt/@rootfs/boot
[ -z "$efi_dev" ] || mount $efi_dev /mnt/@rootfs/boot/efi

mount --bind /dev /mnt/@rootfs/dev
mount --bind /dev/pts /mnt/@rootfs/dev/pts
mount --bind /proc /mnt/@rootfs/proc
mount --bind /sys /mnt/@rootfs/sys

chroot /mnt/@rootfs /usr/bin/apt install btrfs-progs
chroot /mnt/@rootfs /usr/sbin/update-initramfs -k all -u
chroot /mnt/@rootfs /usr/sbin/update-grub

reboot -f

