---

# We need GPG for apt_key
- name: Install GPG
  apt:
    name: gpg
    update_cache: yes

- name: Download influx key
  shell: "wget -q -O - https://repos.influxdata.com/influxdata-archive_compat.key | gpg --dearmor > /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg"

- name: Add influx repository
  apt_repository:
    filename: influxdata
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main"

- name: Install influxdb
  apt:
    name: influxdb2
    update_cache: yes

- name: Start and enable influxdb
  systemd:
    name: influxdb.service
    state: restarted
    enabled: yes
