- name: "Install InfluxDB"
  import_playbook: "install.yml"
  when: upgrade_influx_and_delete_everything == False

- name: "Upgrade InfluxDB"
  import_playbook: "migrate.yml"
  when: upgrade_influx_and_delete_everything == True
