---

- name: "Install InfluxDB"
  include_tasks: "install.yml"
  when: not upgrade_influx_and_delete_everything

- name: "Upgrade InfluxDB"
  include_tasks: "migrate.yml"
  when: upgrade_influx_and_delete_everything
