---

- name: "Install InfluxDB"
  include_tasks: "install.yml"
  when: upgrade_influx_and_delete_everything is not defined 

- name: "Upgrade InfluxDB"
  include_tasks: "migrate.yml"
  when: upgrade_influx_and_delete_everything is defined and upgrade_influx_and_delete_everything == True
