- name: Get host LE domain
  shell: "ls /etc/letsencrypt/live/ | grep -v README"
  register: le_host_domain_detected
  when: le_domain is not defined

- name: Check host LE domain
  set_fact:
    le_host_domain: "{{ le_host_domain_detected.stdout_lines[0] }}"
  when: le_domain is not defined

- name: Extract LE domain
  set_fact:
    le_domain: "{{ le_host_domain.split('.')[1:] | join('.') }}"
  when: le_domain is not defined
