---

# Ansible needs this for the postgres modules below
- name: Install needed packages
  apt:
    name:
      - postgresql
      - python3-psycopg2
      - sudo
    state: latest
    update_cache: yes

- name: Start and enable postgres
  systemd:
    name: postgresql.service
    state: started
    enabled: yes

# This block is run as the user postgres
- name: Postgres operations
  block:
    - name: Set postgres chirpstack user
      block:

        - name: Generate passwords
          set_fact:
            postgres_passwords: "{{ postgres_passwords | default({}) | combine({ item: lookup('ansible.builtin.password', '/dev/null', length=16) }) }}"
          loop:
            - chirpstack_as

        - name: Add chirpstack postgres user
          postgresql_user:
            name: chirpstack_as
            password: "{{ postgres_passwords['chirpstack_as'] }}"

      when: overwrite_passwords

    - name: Create chirpstack database
      postgresql_db:
        name: chirpstack_as
        owner: chirpstack_as

    - name: Add extensions to chirpstack DB
      postgresql_ext:
        name: "{{ item }}"
        db: chirpstack_as
      loop:
        - "pg_trgm"
        - "hstore"

  become: true
  become_user: postgres
