---

# This block is run as the user postgres
- name: Postgres operations
  block:
    - name: Set postgres chirpstack user
      block:

        - name: Generate passwords
          set_fact:
            postgres_passwords: "{{ postgres_passwords | default({}) | combine({ item: lookup('ansible.builtin.password', '/dev/null length=16 chars=ascii_lowercase,ascii_uppercase,digits' ) }) }}"
          loop:
            - chirpstack_as
            - chirpstack_ns

        - name: Add chirpstack postgres user
          postgresql_user:
            name: "{{ item.key }}"
            password: "{{ item.value }}"
          loop:
            "{{ postgres_passwords | dict2items }}"

      when: overwrite_passwords

    - name: Create chirpstack databases
      postgresql_db:
        name: "{{ item }}"
        owner: "{{ item }}"
      loop:
        - "chirpstack_as"
        - "chirpstack_ns"

    - name: Add extensions to chirpstack DB
      postgresql_ext:
        name: "{{ item }}"
        db: chirpstack_as
      loop:
        - "pg_trgm"
        - "hstore"

  become: true
  become_user: postgres
