---

- name: "Install dependences"
  apt:
    name:
      - "apt-transport-https"
      - "software-properties-common"
      - "wget"
    update_cache: yes

- name: "Download Grafana GPG key"
  get_url:
    url: "https://apt.grafana.com/gpg.key"
    dest: "/usr/share/keyrings/grafana.key"

- name: "Make sure Grafana apt source exists"
  lineinfile:
    path: "/etc/apt/sources.list.d/grafana.list"
    line: "deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main"
    create: yes

- name: "Install Grafana"
  apt:
    name: "grafana"
    update_cache: yes
