---

- name: "Install dependences"
  apt:
    name:
      - "apt-transport-https"
      - "software-properties-common"
      - "wget"
    update_cache: yes

- name: "Download Grafana GPG key"
  shell: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null"

- name: "Make sure Grafana apt source exists"
  lineinfile:
    path: "/etc/apt/sources.list.d/grafana.list"
    line: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main"
    create: yes

- name: "Install Grafana"
  apt:
    name: "grafana-nightly"
    update_cache: yes
