---

- name: "Configure Grafana"
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: "640"


- name: "Create Grafana Admin Password"
  ansible.builtin.set_fact:
    grafana_admin_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=16, chars=['ascii_letters', 'digits']) }}"

- name: "Set Grafana Password"
  command: "grafana-cli admin reset-admin-password {{ grafana_admin_password }}; chown grafana: /var/lib/grafana/grafana.db;"


- name: "Add InfluxDB 2.0 data source to Grafana"
  community.grafana.grafana_datasource:
    name: "influxdb"
    type: "influxdb"
    url: "http://localhost:8086"
    access: "proxy"
    json_data:
      organization: "devtank"
      default_bucket: "sf"
      version: "Flux"
    secure_json_data:
      token: "{{ new_token }}"
    is_default: yes
    state: present
  vars:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"


- name: "Start and enable Grafana"
  systemd:
    name: "grafana-server"
    state: restarted
    enabled: yes
    daemon_reload: yes
