- hosts: "{{ target }}"
  roles:
    - { role: system, tags: system }
    - { role: redis, tags: redis }
    - { role: mosquitto, tags: mosquitto }
    - { role: influx, tags: influx }
    - { role: postgres, tags: postgres }
    - { role: chirpstack, tags: chirpstack }
    - { role: grafana, tags: grafana }
    - { role: cleanup, tags: cleanup }
