---
- name: Print influx passwords
  debug:
    msg: "Influx password for {{ item.key }}: {{ item.value }}"
  loop: "{{ influx_passwords | dict2items }}"
  when: influx_passwords is defined and (influx_config_list.stdout_lines | length == 0 or overwrite_passwords)

- name: Print Influx token
  debug:
    msg: "InfluxDB Token: {{ influx_new_token }}"
  when: influx_new_token is defined

- name: Print postgres passwords
  debug:
    msg: "Postgres password for {{ item.key }}: {{ item.value }}"
  loop: "{{ postgres_passwords | dict2items }}"
  when: overwrite_passwords

- name: Print MQTT password
  debug:
    msg: "MQTT password for {{ customer_name }}: {{ mosquitto_passwd }}"

- name: Print Grafana passwords
  debug:
    msg: "Grafana admin for {{ customer_name }}: {{ grafana_admin_password }}\nGrafana viewer for {{ customer_name }}: {{ grafana_viewer_password }}"

- name: Write passwords to JSON file
  vars:
    json_pwds: |
      {
        "Influx": {{ influx_passwords | to_json }},
        "Influx Token": {{ influx_new_token | to_json }},
        "Postgres": {{ postgres_passwords | to_json }},
        "Mosquitto": {"{{ customer_name }}": {{ mosquitto_passwd | to_json }}},
        "Grafana Admin": {"admin": {{ grafana_admin_password | to_json }}},
        "Grafana Viewer": {"viewer": {{ grafana_viewer_password | to_json }}},
        "Chirpstack Admin": {"admin": {{ chirpstack_admin_password | to_json}}}
      }
  ansible.builtin.copy:
    content: "{{ json_pwds | to_nice_json }}"
    dest: "/root/passwords.json"
