---
- name: Print influx passwords
  debug:
    msg: "Influx password for {{ item.key }}: {{ item.value }}"
  loop: "{{ influx_passwords | dict2items }}"
  when: influx_passwords is defined and (influx_config_list.stdout_lines | length == 0 or overwrite_passwords)

- name: Print Influx token
  debug:
    msg: "InfluxDB Token: {{ new_token }}"
  when: new_token is defined

- name: Print postgres passwords
  debug:
    msg: "Postgres password for {{ item.key }}: {{ item.value }}"
  loop: "{{ postgres_passwords | dict2items }}"
  when: overwrite_passwords

- name: Print MQTT password
  debug:
    msg: "MQTT password for {{ customer_name }}: {{ mosquitto_passwd }}"

- name: Print Grafana password
  debug:
    msg: "Grafana admin for {{ customer_name }}: {{ grafana_admin_password }}"

- name: Write passwords to file
  ansible.builtin.copy:
    content: "Influx: {{ influx_passwords }}\nInflux Token: {{ new_token }}\nPostgres: {{ postgres_passwords }}\nMosquitto: {{ mosquitto_passwd }}\nGrafana Admin: {{ grafana_admin_password }}\n"
    dest: "/root/passwords"
