---
- name: Print influx passwords
  debug:
    msg: "Influx password for {{ item.key }}: {{ item.value }}"
  loop: "{{ influx_passwords | dict2items }}"
  when: influx_passwords is defined and (influx_config_list.stdout_lines | length == 0 or overwrite_passwords)

- name: Print postgres passwords
  debug:
    msg: "Postgres password for {{ item.key }}: {{ item.value }}"
  loop: "{{ postgres_passwords | dict2items }}"
  when: overwrite_passwords

- name: Print MQTT password
  debug:
    msg: "MQTT password for {{ customer_name }}: {{ mosquitto_passwd }}"
